//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIPracticaProgramada4
{
    using System;
    using System.Collections.Generic;
    
    public partial class List
    {
        public int ListId { get; set; }
        public string ListName { get; set; }
        public string ListDescription { get; set; }
        public Nullable<int> ClassificationId { get; set; }
    
        public virtual Clasification Clasification { get; set; }
    }
}
